### ISSUE TITLE
Bottom navigation elevation

### ISSUE THREAD

**Issue by MegaAndroidDeveloper666** [AlexGladkov/Odyssey#55]
There is no way to configure elevation of Bottom Navigation since Odyssey library code passes no value in BottomBarNavigotor.kt line 60. (v 1.0.0)
`BottomNavigation(
            backgroundColor = bottomNavConfiguration.backgroundColor
        )`
Thus androidx's composable BottomNavigation takes default value from BottomNavigationDefaults.Elevation = 8.dp

Please add possibility to change bottom navigation elevation.

**Comment by AlexGladkov** [comment]
Fixed in 1.0.1
