### ISSUE TITLE
`parentRootController` for `MultiStackRootController` is always `null`

### ISSUE THREAD

**Issue by VitalyPeryatin** [AlexGladkov/Odyssey#56]
I haven't access to my parent RootController's NavigationGraph, because `MultiStackRootController.findRootController()` doesn't return correct `parentRootController`.

----------
_Example for bug reproducing_ (branch: `odyssey_navigation_issue`): https://github.com/VitalyPeryatin/FinanceTracker/tree/odyssey_navigation_issue
_This row crashes application:_
`rootController.findRootController().push(MainNavigationTree.AddTransaction.name)`

**Comment by AlexGladkov** [comment]
Fixed in 1.0.1
