### ISSUE TITLE
backToScreen method is rolling down application instead of go to some screen

### ISSUE THREAD

**Issue by Bittner322** [AlexGladkov/Odyssey#62]
So, i tried to use backToScreen(key) method to go back for needed screen, but instead of it application just rolls down.

https://github.com/VitalyPeryatin/1Coin/tree/feature/FT-68_implement_account_edit_screen

https://user-images.githubusercontent.com/100136541/201480753-628a2b5a-ea16-4788-86e8-a72c8d72d949.mp4

**Comment by Bittner322** [comment]
The problem in 183 line in AddAccountScreen.kt file

**Comment by AlexGladkov** [comment]
Fixed in 1.3
