### ISSUE TITLE
Support of edge-to-edge mode not working

### ISSUE THREAD

**Issue by VitalyPeryatin** [AlexGladkov/Odyssey#65]
It is impossible to create edge-to-edge application. Status bar and navigation bar are just black at this case. 

![telegram-cloud-photo-size-2-5255810566436538111-y](https://user-images.githubusercontent.com/22561563/208295044-45b487d7-75a3-4f7f-89cd-5c29b95de0cb.jpg)

**Comment by AlexGladkov** [comment]
Fixed in 1.3
