### ISSUE TITLE
Missing ViewActions

### ISSUE THREAD

**Issue by VitalyPeryatin** [AlexGladkov/Odyssey#66]
No opportunity to change `extraBufferCapacity` param for `_viewActions` SharedFlow, so when ViewModel send several actions in sequence, only the last action will be executed. I think there is needs more flexibility. 

For example:
```
FeatureViewModel {
    fun someMethod() {
        ...
        viewAction = FeatureAction.Vibrate()
        viewAction = FeatureAction.Close()
        ...
    }
}
```

There is `FeatureAction.Vibrate` will be missed

**Comment by AlexGladkov** [comment]
ViewModel is not a part of Odyssey
